import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Shown at the top of every package's sidebar so visitors always see the full
// list of packages, whichever package they are currently reading.
const allPackages = {
  type: 'category' as const,
  label: 'Packages',
  collapsible: false,
  collapsed: false,
  items: [
    {type: 'link' as const, label: 'Tools', href: '/tools/intro'},
    {type: 'link' as const, label: 'Singletons', href: '/singletons/intro'},
    {type: 'link' as const, label: 'Channeled Properties', href: '/channeled-properties/intro'},
    {type: 'link' as const, label: 'Graphs', href: '/graphs/intro'},
    {type: 'link' as const, label: 'Cards', href: '/cards/intro'},
  ],
};

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    allPackages,
    {type: 'html', value: '<hr class="sidebar-separator" />'},
    {type: 'autogenerated', dirName: '.'},
  ],
};

export default sidebars;
